{"uid":"fda66c63da21d4d4","name":"0202 should get name","fullName":"cypress-js after hook failure 0202 should get name","historyId":"41e86a0a-dce4-5e21-ac8e-ef1ca31ccb9d","time":{"start":1720686753530,"stop":1720686754007,"duration":477},"status":"failed","statusMessage":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","statusTrace":"Error: Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`\n    at Context.eval (webpack://cypress-grep-example/./cypress/e2e/before-after-hook/after-fail.cy.js:12:12)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","statusTrace":"Error: Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`\n    at Context.eval (webpack://cypress-grep-example/./cypress/e2e/before-after-hook/after-fail.cy.js:12:12)","steps":[{"name":"\"before each\" hook","time":{"start":1720686753531,"stop":1720686753797,"duration":266},"status":"passed","steps":[{"name":"intercept: mytest.com**","time":{"start":1720686753536,"stop":1720686753538,"duration":2},"status":"passed","steps":[{"name":"route","time":{"start":1720686753538,"stop":1720686753538,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[{"uid":"599d01adb740e2a0","name":"intercept: mytest.com** args","source":"599d01adb740e2a0.json","type":"application/json","size":1839}],"parameters":[],"stepsCount":1,"shouldDisplayMessage":false,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"visit: mytest.com","time":{"start":1720686753538,"stop":1720686753785,"duration":247},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"stepsCount":3,"shouldDisplayMessage":false,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"get: [data-test-id=\"data-name-section\"] input","time":{"start":1720686753786,"stop":1720686753791,"duration":5},"status":"passed","steps":[{"name":"assert: expected **<input>** to exist in the DOM","time":{"start":1720686753791,"stop":1720686753791,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"assert: expected **<input>** to have attribute **placeholder** with the value **name**","time":{"start":1720686753791,"stop":1720686753791,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"stepsCount":2,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"92188d0e590f901d","name":"after hook failure -- 0202 should get name -- after all hook teardown app (failed).png","source":"92188d0e590f901d.png","type":"image/png","size":64805}],"parameters":[],"stepsCount":7,"shouldDisplayMessage":true,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"\"after all\" hook: teardown app","time":{"start":1720686753862,"stop":1720686753985,"duration":123},"status":"failed","statusMessage":"Fail in after hook","statusTrace":"Error: Fail in after hook\n    at Context.eval (webpack://cypress-grep-example/./cypress/e2e/before-after-hook/after-fail.cy.js:12:12)","steps":[{"name":"log: setup step after all tests in suite","time":{"start":1720686753803,"stop":1720686753806,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"video","time":{"start":1720686755079,"stop":1720686755079,"duration":0},"status":"passed","steps":[],"attachments":[{"uid":"eea4a32cfda69eff","name":"after-fail.cy.js.mp4","source":"eea4a32cfda69eff.mp4","type":"video/mp4","size":92723}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"package","value":"cypress.e2e.before-after-hook.after-fail.cy.js"},{"name":"path","value":"cypress/e2e/before-after-hook/after-fail.cy.js"},{"name":"host","value":"my-host"},{"name":"thread","value":"01"},{"name":"epic","value":"hooks"},{"name":"feature","value":"after"},{"name":"parentSuite","value":"cypress-js"},{"name":"suite","value":"after hook failure"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":4,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"137b6cc0d7c41be","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1720186810133,"stop":1720186810579,"duration":446}},{"uid":"80c7a505df50e8e","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1720105374736,"stop":1720105375165,"duration":429}},{"uid":"8e5bb552855a29e6","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1719481474160,"stop":1719481474629,"duration":469}}]},"tags":[]},"source":"fda66c63da21d4d4.json","parameterValues":[]}